export { default as Home } from './home/Home'
export { default as UserDetails } from './Users/UserDetails'
export { default as UserList } from './Users/UserList'
export { default as NewUser } from './NewUser/NewUser'
export { default as Products } from './Products/Products'
export { default as ProductDetails } from './Products/ProductDetails'
export { default as NotFound } from './NotFound/NotFound'
